services:
  nginx:
    image: nginx:1.25.5-alpine
    ports:
      - ${APP:-8000}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    networks:
      - net
    depends_on:
      - app
  app:
    image: hztetris-client:latest
    restart: always
    networks:
      - net
networks:
  net:
